name: PR CI

on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'docs/**'

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  validate:
    name: Setup Python & Validate Schemas
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies and validate
        run: make validate

  lint-typecheck:
    name: Lint & Typecheck
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: web/package-lock.json
      - name: Install Python lint dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff mypy
      - name: Ruff
        run: ruff .
      - name: Mypy
        run: mypy .
      - name: Install Web dependencies
        run: |
          cd web
          npm ci
      - name: Web lint
        run: |
          cd web
          npm run lint
      - name: Web type-check
        run: |
          cd web
          npm run type-check

  ingest:
    name: Ingest (dry-run)
    runs-on: ubuntu-latest
    needs: [lint-typecheck]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ingest/requirements.txt
      - name: Run ingest
        run: PR_CI=1 python ingest/run_ingest.py

  enrich:
    name: Enrich (dry-run)
    runs-on: ubuntu-latest
    needs: ingest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ingest/requirements.txt
      - name: Run enrich
        run: PR_CI=1 python enrich/run_enrich.py

  scoring:
    name: Scoring (dry-run)
    runs-on: ubuntu-latest
    needs: enrich
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ingest/requirements.txt
      - name: Run scoring
        run: PR_CI=1 python scoring/run_scoring.py

  build-web:
    name: Build Web (no deploy)
    runs-on: ubuntu-latest
    needs: scoring
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: web/package-lock.json
      - name: Install dependencies
        run: |
          cd web
          npm ci
      - name: Build and export
        run: |
          cd web
          npm run build
          npm run export
